// <auto-generated />
namespace FVat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NameColumnInVATEntitiesBecomesUnique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NameColumnInVATEntitiesBecomesUnique));
        
        string IMigrationMetadata.Id
        {
            get { return "201903241247040_Name-Column-In-VATEntities-Becomes-Unique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
