// <auto-generated />
namespace FVat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NIPColumnInVATEntitiesMaxLengthChangedTo14 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NIPColumnInVATEntitiesMaxLengthChangedTo14));
        
        string IMigrationMetadata.Id
        {
            get { return "201903241426252_NIP-Column-In-VATEntities-Max-Length-Changed-To-14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
