// <auto-generated />
namespace FVat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedNIPPESELEMailAndPhoneNumberColumnsToVATEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedNIPPESELEMailAndPhoneNumberColumnsToVATEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201903231834251_Added-NIP-PESEL-EMail-And-PhoneNumber-Columns-To-VATEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
